name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        # See build.yml for why --ignore-engines is needed here.
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build the file
        run: yarn build

      - name: Compress bundle
        run: gzip -kf multiple-entity-row.js

      - name: Upload build artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            multiple-entity-row.js
            multiple-entity-row.js.gz
